dist: trusty
sudo: required

language: rust
rust:
  - stable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - ragel
    - python3
    - libpcap0.8-dev
    - autoconf
    - automake
    - gettext
    - libtool

before_install:
  - sudo add-apt-repository ppa:kzemek/boost -y
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -q
  - sudo apt-get install libboost1.58-dev cmake -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 1 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo update-alternatives --set gcc /usr/bin/gcc-6
  - sudo update-alternatives --set g++ /usr/bin/g++-6
  - mkdir build && cd build && cmake ..

install:
  - make 
