dist: trusty
sudo: required

language: rust
rust:
  - stable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - ragel
    - python3
    - libboost-all-dev
    - libpcap0.8-dev
    - autoconf
    - automake
    - gettext
    - libtool

before_install:
  - mkdir build && cd build && cmake ..

install:
  - make 
